In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
test=pd.read_csv('test.csv')
train=pd.read_csv('train.csv')

In [3]:
test.shape[0]

418

In [4]:

test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
train.shape[0]

891

In [6]:

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [8]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

In [9]:
test.drop(columns=['PassengerId','Cabin'],inplace=True)

In [10]:
train.drop(columns=['PassengerId','Cabin'],inplace=True)

In [11]:
train.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      2
dtype: int64

In [12]:
test.isnull().sum()

Pclass       0
Name         0
Sex          0
Age         86
SibSp        0
Parch        0
Ticket       0
Fare         1
Embarked     0
dtype: int64

In [13]:
train['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [14]:
train['Embarked'] = train['Embarked'].fillna('S')

In [15]:
train['Embarked'].isnull().sum()

np.int64(0)

In [16]:
train.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      0
dtype: int64

In [17]:
train['Fare'] = train['Fare'].fillna(train['Fare'].mean())

In [18]:
test['Fare'] = test['Fare'].fillna(test['Fare'].mean())

In [19]:
train.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      0
dtype: int64

In [20]:
test.isnull().sum()

Pclass       0
Name         0
Sex          0
Age         86
SibSp        0
Parch        0
Ticket       0
Fare         0
Embarked     0
dtype: int64

In [21]:
train_Age=np.random.randint(train['Age'].mean()-train['Age'].std(),train['Age'].mean()+train['Age'].std(),177)

In [42]:
test_Age=np.random.randint(test['Age'].mean()-test['Age'].std(),test['Age'].mean()+test['Age'].std(),177)

In [23]:
print(train_Age)

[36 21 24 27 41 15 30 17 28 29 26 23 43 41 19 16 16 43 43 22 27 23 42 22
 18 40 32 37 35 37 15 33 16 42 38 42 34 16 22 38 30 29 17 34 18 16 21 25
 27 25 23 25 17 38 35 17 32 37 33 21 38 41 33 30 40 29 27 21 32 20 42 37
 22 23 23 26 30 27 16 29 22 18 30 25 39 39 36 28 35 42 40 43 40 38 22 27
 41 21 35 43 32 19 43 21 28 38 17 28 28 42 29 30 17 27 36 37 40 32 24 41
 31 23 15 33 28 20 42 43 25 36 27 34 28 15 32 42 22 19 23 23 34 40 18 41
 35 43 23 18 39 38 27 15 19 20 42 30 18 18 20 42 25 35 27 31 34 33 33 33
 36 30 41 40 23 17 42 30 20]

In [47]:
print(test_Age)

[26 21 38 19 16 30 28 32 24 23 29 38 36 16 16 18 41 21 40 41 18 36 36 38
 27 31 42 35 38 36 43 27 23 31 31 23 34 21 18 17 33 16 37 25 26 42 17 22
 40 33 40 25 26 26 34 21 17 35 23 42 28 39 21 28 28 20 40 20 16 17 36 29
 42 26 32 28 28 27 40 41 42 28 23 16 21 28 17 37 22 25 31 16 33 32 40 36
 31 41 41 25 30 25 31 37 43 22 37 18 42 35 29 17 25 29 39 38 33 16 42 18
 40 35 30 42 28 41 21 26 36 40 43 39 19 18 31 34 34 43 22 27 16 43 29 19
 33 36 25 17 38 20 22 27 39 42 20 16 16 32 24 17 20 41 33 39 24 30 39 17
 38 41 20 22 38 43 43 24 26]

In [32]:

train.loc[train['Age'].isnull(),'Age']=train_Age.mean()

In [46]:
test.loc[test['Age'].isnull(),'Age']=test_Age.mean()

In [45]:
train.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [48]:
test.isnull().sum()

Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64