In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
test=pd.read_csv('test.csv')
train=pd.read_csv('train.csv')

In [3]:
test.shape[0]

418

In [4]:

test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
train.shape[0]

891

In [6]:

train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [8]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

In [9]:
test.drop(columns=['PassengerId','Cabin'],inplace=True)

In [10]:
train.drop(columns=['PassengerId','Cabin'],inplace=True)

In [11]:
train.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      2
dtype: int64

In [12]:
test.isnull().sum()

Pclass       0
Name         0
Sex          0
Age         86
SibSp        0
Parch        0
Ticket       0
Fare         1
Embarked     0
dtype: int64

In [13]:
train['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [14]:
train['Embarked'] = train['Embarked'].fillna('S')

In [15]:
train['Embarked'].isnull().sum()

np.int64(0)

In [16]:
train.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      0
dtype: int64

In [17]:
train['Fare'] = train['Fare'].fillna(train['Fare'].mean())

In [18]:
test['Fare'] = test['Fare'].fillna(test['Fare'].mean())

In [19]:
train.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      0
dtype: int64

In [20]:
test.isnull().sum()

Pclass       0
Name         0
Sex          0
Age         86
SibSp        0
Parch        0
Ticket       0
Fare         0
Embarked     0
dtype: int64

In [21]:
train_Age=np.random.randint(train['Age'].mean()-train['Age'].std(),train['Age'].mean()+train['Age'].std(),177)

In [22]:
test_Age=np.random.randint(test['Age'].mean()-test['Age'].std(),test['Age'].mean()+test['Age'].std(),177)

In [23]:
print(train_Age)

[19 25 28 43 15 25 16 26 30 19 19 15 38 28 40 18 38 32 32 31 42 28 18 33
 39 22 31 30 39 36 20 30 28 36 34 22 34 31 23 23 16 23 37 43 28 39 43 41
 27 24 38 37 36 15 34 15 20 23 25 18 40 36 40 27 21 37 25 21 22 42 23 25
 33 35 42 41 25 18 33 27 29 22 33 31 28 40 42 35 15 16 27 23 24 22 22 34
 40 37 23 42 37 19 31 29 16 21 41 33 24 27 20 28 35 42 43 35 21 19 18 18
 19 32 24 38 35 38 16 30 34 18 41 27 31 34 41 28 31 27 26 32 23 21 32 15
 27 18 34 28 23 28 31 26 28 19 32 33 30 17 21 41 23 17 42 34 32 42 37 20
 33 18 38 22 28 15 41 26 39]

In [24]:
print(test_Age)

[37 27 17 34 43 40 17 24 30 29 24 41 30 42 39 34 30 29 29 27 38 24 32 27
 16 30 38 23 17 29 36 27 43 42 35 22 25 26 18 42 26 41 28 17 34 23 40 19
 21 33 27 34 25 18 34 35 43 25 39 24 25 18 29 18 32 19 24 40 41 18 39 32
 33 23 21 23 16 30 31 26 30 19 19 27 26 35 25 20 28 37 17 30 38 34 32 21
 29 30 21 21 42 36 30 40 41 25 42 42 38 20 23 22 24 37 35 18 21 20 31 24
 35 36 27 40 39 20 35 28 25 37 37 21 31 39 38 19 23 34 20 31 42 25 17 21
 16 20 20 42 22 30 26 28 24 21 42 39 35 23 18 23 40 21 41 25 40 30 16 41
 24 28 21 20 26 16 28 36 22]

In [25]:

train.loc[train['Age'].isnull(),'Age']=train_Age.mean()

In [26]:
test.loc[test['Age'].isnull(),'Age']=test_Age.mean()

In [27]:
train.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [28]:
test.isnull().sum()

Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [29]:
def Survive_ratio(train, x):
    return train[train['Pclass']==x]['Survived'].value_counts()
for i in range(1,4):
    print(Survive_ratio(train, i))

Survived
1    136
0     80
Name: count, dtype: int64
Survived
0    97
1    87
Name: count, dtype: int64
Survived
0    372
1    119
Name: count, dtype: int64